### ISSUE TITLE
Change Implicits to JustSyntax

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/just-fp#41]
# Task
## Summary 
Change `Implicits` to `JustSyntax`

## Project Details
Version: `0.4.0`

## Description
So when using it, just import
```scala
import kevinlee.fp.JustSyntax._
```
### TODOs
- [x] Create `syntax` package
- [x] Rename `EitherImplicits` to `EitherSyntax`
- [x] Move `eithers.scala` file, which has `EitherSyntax`, to the `syntax` package
- [x] Add `JustSyntax` containing all syntaxes.
